---
title: "Pre_trial"
author: "Juan Pablo Jordán"
date: "3/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

Weight lost (initial weight - final weight)
```{r}

#data wrangling
weight <- read_csv("Larval Weight.csv")

weight_loss <- weight %>% 
  select(-notes) %>% 
  filter(!is.na(final_weight)) %>% 
  transform(final_weight = as.numeric(final_weight)) %>% 
  mutate(weight_lost = after_24_starve - final_weight) 
  
#anova model

aov_1 <- aov(weight_lost ~ treatment, data = weight_loss)
summary(aov_1)

#Visualization

ggplot(weight_loss, aes(x = treatment, y = weight_lost)) +
  geom_boxplot() +
  geom_point()+
  labs (x = "Treatment", y = "Weight lost")
  

```



Choice assays
```{r}
#data wrangling
choice <- read_csv("Choice assay.csv")

choice_clean <- choice %>% 
  group_by(Treatment) %>%
  subset(Choice!="lost") %>% 
  count(Choice) 



#visualization
ggplot(arrange(choice_clean, n), aes(x = Treatment, y = n, fill = Choice)) +
  geom_bar(position="stack", stat="identity")+
  labs (x = "Treatment", y = "Choice Number")

```

Weight

```{r}

#data wrangling
weight <- read_csv("pre trial.csv")

weight_clean <- weight %>% 
  select(-Date, -Latitude, -Longitude, -Notes, -`Scale Length (cm)`, -Time) 

#model
aov_2 <- aov(Percent_Consumed ~ Treatment, data = weight_clean)
summary(aov_2)

#visualization
ggplot(weight_clean, aes(x = Treatment, y = Percent_Consumed)) +
  geom_boxplot() +
  geom_point()+
  labs (x = "Treatment", y = "Percent of Leaf Consumed")

```


